### ISSUE TITLE
Watson sees non-food items

### ISSUE THREAD

**Issue by dolph** [IBM/watson-calorie-counter#21]
I tried giving Watson this image, which I took through the Calorie Counter app:

![Grapes](https://i.imgur.com/zNSZf71.jpg)

This is a snippet from what the Calorie Counter app saw, which, in this case, includes the color at the bottom (not a food item) and not "grapes":

![Non-food items](https://i.imgur.com/6hjVQzZ.png)

The Watson Visual Recognition demo shows a similar list of non-food items as the app on the left (which does not contain "grapes" either), but also shows an accurate list of food items on the right (which contains "grapes" with 100% confidence):

![Visual recognition demo](https://i.imgur.com/XJvecRk.png)

**Comment by RiyaMRoy04** [comment]
Have used food classifier thereby increasing accuracy and response of analyzed image. @dolph @rhagarty 

![21640695_1533065730084252_1463340096_o](https://user-images.githubusercontent.com/11567379/30510796-987099c8-9ae8-11e7-8b61-12e91676d1a7.png)

![21682568_1533073110083514_1602099202_o](https://user-images.githubusercontent.com/11567379/30510797-9fad4f74-9ae8-11e7-8610-7693dc76bef8.png)

**Comment by ab-bh** [comment]
I am unable to deploy the ibm watson calorie counter:
i am gtting this error:
Preparing to start the job...
Logging into Bluemix as user: "abhishekanitahc@gmail.com" 
Preparing the build artifacts...
Target: https://api.eu-gb.bluemix.net
Creating service instance wcc-visual-recognition in org abhishekanitahc@gmail.com / space dev as abhishekanitahc@gmail.com...
FAILED
Could not find plan with name free

Finished: FAILED



can you help!!!
