### ISSUE TITLE
`cordova platform add android` fails

### ISSUE THREAD

**Issue by scottdangelo** [IBM/watson-calorie-counter#46]
Command fails:
```
Scotts-MBP:mobile scottda$ cordova platform add android
-bash: cordova: command not found
```

Does Cordova need to be installed globally for this to work? That needs to be documented explicitly, and the link to Cordova should point to `https://cordova.apache.org/docs/en/latest/guide/cli/index.html`
where this is stated, instead of the [platform page](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#setting-environment-variables)

**Comment by RiyaMRoy04** [comment]
@scottdangelo **Cordova** and **Node.JS** is mentioned in the [Using manually-installed dependencies](https://github.com/IBM/watson-calorie-counter#using-manually-installed-dependencies), that hyperlinks also redirects to the [Installing the Cordova CLI](https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli) and [NodeJS download](https://nodejs.org/en/download/) respectively. Let me know if we still have to mention it explicitly.

**Comment by RiyaMRoy04** [comment]
Closing this issue since Cordova and Node.JS is mentioned as pre-requisites in the doc [Using manually-installed dependencies](https://github.com/IBM/watson-calorie-counter#using-manually-installed-dependencies).
